VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config| 
  config.vm.define :gitlab do |cfg|
    cfg.vm.box = "bento/ubuntu-22.04"
    cfg.vm.hostname = "ansible.local"

    if Vagrant.has_plugin?("vagrant-vbguest")
      cfg.vbguest.auto_update = false
    end

    cfg.vm.network "private_network", ip: "192.168.33.46"
    cfg.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/"]

    cfg.vm.provider "virtualbox" do |vb| 
      vb.memory = 2048
    end

    cfg.vm.provision "shell", inline: <<-'SHELL'
      export DEBIAN_FRONTEND=noninteractive
      sudo apt-get update
      sudo apt-get install -y curl
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt-get update -y
      sudo apt-get install -y ansible-core
SHELL
  end
end