VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config| 
  config.vm.define :gitlab do |cfg|
    cfg.vm.box = "bento/ubuntu-22.04"
    cfg.vm.hostname = "ci-runner"

    if Vagrant.has_plugin?("vagrant-vbguest")
      cfg.vbguest.auto_update = false
    end

    cfg.vm.network "private_network", ip: "192.168.33.45"
    cfg.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/"]

    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "ci-runner"
      vb.memory = 2048
    end

    cfg.vm.provision "shell", inline: <<-'SHELL'
      sudo apt-get update
      sudo apt-get install -y curl

      sudo curl -L --output /usr/local/bin/gitlab-runner \
        "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-arm64"
      sudo chmod +x /usr/local/bin/gitlab-runner
      
      sudo useradd --comment 'GitLab Runner' \
        --create-home gitlab-runner \
        --shell /bin/bash
 
      sudo gitlab-runner install \
        --user=gitlab-runner \
        --working-directory=/home/gitlab-runner
      sudo gitlab-runner start
 
      sudo gitlab-runner register --non-interactive \
        --url "http://192.168.33.44/" \
        --registration-token "GR1348941AWmwXEVA5NCXh_PXZusZ" \
        --executor "shell" \
        --description "shell-runner" \
        --maintenance-note "Free-form maintainer notes about this runner" \
        --tag-list "shell,aws" \
        --run-untagged="true" \
        --locked="false" \
        --access-level="not_protected"
SHELL
  end
end